// ATLProject1.idl : IDL source for ATLProject1
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLProject1.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(C5F3C329-4F82-4097-8B6D-0E454F5C4C1C),
	version(1.0),
]
library ATLProject1Lib
{
	importlib("stdole2.tlb");
};

