// Test.idl : IDL source for Test
//

// This file will be processed by the MIDL tool to
// produce the type library (Test.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(F3823883-9132-4427-AF92-7C9C7B996C22),
	version(1.0),
]
library TestLib
{
	importlib("stdole2.tlb");
};

